### ISSUE TITLE
Make blog posts more readable

### ISSUE THREAD

**Issue by killercup** [mgattozzi/mgattozzi#2]
I just saw <https://mgattozzi.com/rust-is> and found it very hard to read. Not because of the content—because of the font size and line length. I'd add something like this to the container of the article (which is currently a `div` with a `class`):

```css
.blog-article {
  font-size: 18px; /* or maybe 16px */
  line-height: 1.5; /* a bit more to make it a bit nicer to follow the lines */
  max-width: 42em; /* shorter lines are much easier to read; also: 42 */
  hyphens: auto; /* hyphenation is nice */
  -webkit-hyphens: auto; /* hyphenation for chrome and safari */
}
```

And, if you want to use something other than the default sans-serif font, `font-family: Georgia;` is surprisingly easy to read.
